import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import '../components/Navbar.css'
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
        <Navbar />
            {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
